// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ofruaxvmqrxsirknhizl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9mcnVheHZtcXJ4c2lya25oaXpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMDE0MjUsImV4cCI6MjA3Mzc3NzQyNX0.W2avyCUP8tOp0D5IbdzX_Tb1vz-RmU9NiJpfUvRvmxM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});